name: Publishing Modyo Cli on Github
on:
  release:
    types: [published]
jobs:
  publish-on-github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@modyo'
    - name: Install dependencies with yarn
      run: yarn 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
    - name: Publish to GitHub Package Registry
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{github.token}}
