name: Multi Labeler
on:
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review ]
    branches: [ master, develop ]
jobs:
  call-labeler:
    uses: Giorgiosaud/centralized-workflows/.github/workflows/labeler.yml@v1