name: Linters and Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
jobs:
  linter-and-test:
    uses: Giorgiosaud/centralized-workflows/.github/workflows/lint-and-test.yml@main
    with:
      lint-css: false
