name: Publishing Modyo Github Automation on Npm
on:
  release:
    types: [published]
jobs:
  cache-install-and-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node_modules for parallels executions
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ hashFiles('**/package-lock.json') }}-node-modules
      - name: Install dependencies
        run: npm install
      - name: Versioning
        run : |
          echo $GITHUB_REF
          TAG=$(echo $GITHUB_REF | cut -c 11-)
          echo $TAG
          git config user.email echo $EMAIL
          git config user.name echo $NAME
          npm version $TAG --allow-same-version --no-git-tag-version
          git checkout -b fix/bump-package-version
          git branch --set-upstream-to=origin/fix/bump-package-version fix/bump-package-version
          git pull
          git add .
          git commit -m "fix: bump package version"
          git push --set-upstream origin/fix/bump-package-version fix/bump-package-version
          gh pr create --title "fix: bump self version" --body "Bump Version#
          gh pr merge --squash --auto --merge --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
