name: Publish

on:
  release:
    types: [published]

jobs:
  call-publish:
    uses: Giorgiosaud/centralized-workflows/.github/workflows/npm-publish.yml@main
    with:
      node-version: 20.x
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}