name: Publishing Modyo Cli on Github
on:
  release:
    types: [published]
jobs:
  cache-install-and-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node_modules for parallels executions
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ hashFiles('**/package-lock.json') }}-node-modules
      - name: Install dependencies
        run: npm install
      - name: Versioning
        run : |
          echo $GITHUB_REF
          TAG=$(echo $GITHUB_REF | cut -c 11-)
          echo $TAG
          git config user.email echo $EMAIL
          git config user.name echo $NAME
          pnpm version $TAG
      - name: Commit Changes to version
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_REG }}
      - name: publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}">.npmrc
          npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit Changes to version
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
 
